[package]
name = "messagebus"
<<<<<<< HEAD
version = "0.5.0"
=======
version = "0.5.1"
>>>>>>> db1727b (Local Handlers)
authors = ["Andrey Tkachenko <andrey@aidev.ru>"]
repository = "https://github.com/andreytkachenko/messagebus.git"
keywords = ["futures", "async", "tokio", "message", "bus"]
categories = ["network-programming", "asynchronous"]
description = "MessageBus allows intercommunicate with messages between modules"
license = "MIT OR Apache-2.0"
exclude = [".gitignore", ".cargo/config", ".github/**", "codecov.yml"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["parking_lot", "rt-multi-thread", "sync"] }
parking_lot = "0.11"
async-trait = "0.1"
futures = "0.3"
anyhow = "1.0"
crossbeam = "0.8.0"

[dev-dependencies]
tokio = { version = "1", features = ["parking_lot", "rt-multi-thread", "sync", "macros"] }
